#!/bin/bash

SRC_FILE=$1
RUN=$2

if [ -z "$SRC_FILE" ]; then
    echo "Please provide C++ file to compile"
    echo "Usage: build.sh <filename.cpp>"
    exit 1
fi

OUTPUT_FILE="$(dirname "$1")/$(basename "$1" .cpp)"

CXX=g++
CXXFLAGS="-Wall -Wextra -std=c++20 -pedantic -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -fmax-errors=1 -Winvalid-pch -DDEBUG -I\"$CP_TOOL_ROOT/template\" -O0"

echo "Compiling $SRC_FILE ..."

"$CXX" $CXXFLAGS "$SRC_FILE" -o "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
    echo "Compilation successful!"
    if [ "$RUN" == "1" ]; then
        echo "-------------------------------------------"
        "$OUTPUT_FILE"
    fi
    exit 0
else
    echo "Compilation failed!"
    exit 1
fi
